#!/usr/bin/env bash

set -e

usage() {
  cat <<EOF >&2
Usage: ${0##*/} <qcow2-path>
Try '${0##*/} --help' for more details.
EOF
  exit "${1:-2}"
}

help() {
  cat <<'EOF'
NAME
  run - Boot an installed x86_64 VM from qcow2 disks

SYNOPSIS
  run <vm-dir>

DESCRIPTION
  Launches qemu-system-x86_64 to boot a VM using the qcow2 disk images 
  stored in the specified VM directory.

  - VM directory should contain one or more qcow2 disk images.
  - Disk images will be added in alphabetical order as QEMU drives.

OPTIONS
  -h, --help            Show this help and exit

ARGUMENTS
  <vm-dir>              Path to the VM directory containing qcow2 disk images

EXAMPLES
  run ./qcow2s/debian12

EXIT STATUS
  0  Success
  1  Invalid VM directory or missing disks
  2  Usage error (missing arguments)
EOF
  exit 0
}

if [[ -n $1 ]]; then
  case "$1" in
    -h|--help) help ;;
    -*) echo "${0##*/}: unknown option: $1" >&2; usage ;;
  esac
  vm_dir_path=$1
  if [[ ! -d "$vm_dir_path" ]]; then
    echo "./${0##*/}: couldn't read \`$vm_dir_path\`: VM does not exist" >/dev/stderr
    exit 1
  fi
else
  usage
  exit 1
fi

qemu_vm_disk_args=$(find ${vm_dir_path} -type f | sort | xargs -n1 bash -c 'echo "-drive format=qcow2,file=$0"' | tr '\n' ' ')

set -x
qemu-system-x86_64 \
  -enable-kvm \
  -m 4G -cpu host -smp cores=4 \
  -audiodev pa,id=snd0 \
  -device ich9-intel-hda \
  -device hda-output,audiodev=snd0 \
  -boot menu=on \
  ${qemu_vm_disk_args}

