#!/usr/bin/env bash

action=$1

set -e

usage() {
  cat <<EOF >&2
Usage: ./${0##*/} --<action> <snapshot-name> <img-path>
Try './${0##*/} --help' for more details.
EOF
  exit "${1:-2}"
}

help() {
  cat <<'EOF'
NAME
./snapshot - list, create, delete, apply QEMU image snapshot(s).

SYNOPSIS
  ./snapshot <image-name> <iso-path>

OPTIONS
  -h, --help            Show this help and exit

ARGUMENTS
  <snapshot-name>       Name of the qcow2 image snapshot
  <image-path>          Path of the qcow2 image

EXAMPLES
  ./snapshot --list ./qcow2s/debian.qcow2
  ./snapshot --create snapshot1 ./qcow2s/debian.qcow2

EXIT STATUS
  0  Success
  2  Usage error (invalid args)
EOF
  exit 0
}

list_snapshots() {
  local img_path=$1
  set -x
  qemu-img snapshot -l $img_path
  set +x
}

create_snapshot() {
  local snapshot_name=$1
  local img_path=$2
  set -x
  qemu-img snapshot -c $snapshot_name $img_path
  set +x
}
delete_snapshot() {
  local snapshot_name=$1
  local img_path=$2
  set -x
  qemu-img snapshot -d $snapshot_name $img_path
  set +x
}
apply_snapshot() {
  local snapshot_name=$1
  local img_path=$2
  set -x
  qemu-img snapshot -a $snapshot_name $img_path
  set +x
}


if [ -n "$action" ]; then
  case "$action" in
    -h|--help) help ;;
    --list)
        if [ ! -f "$2" ]; then
          usage
        fi
        list_snapshots "$2"
      ;;
    --create)
        if [ -n "$2" ]; then
          if [ ! -f "$3" ]; then
            echo "./${0##*/}: couldn't read \`$3\`: No such file or directory" >/dev/stderr
            exit 1
          fi
          create_snapshot "$2" "$3"
        else
          usage
        fi
      ;;
    --delete)
        if [ -n "$2" ]; then
          if [ ! -f "$3" ]; then
            echo "./${0##*/}: couldn't read \`$3\`: No such file or directory" >/dev/stderr
            exit 1
          fi
          delete_snapshot "$2" "$3"
        else
          usage
        fi
      ;;
    --apply)
        if [ -n "$2" ]; then
          if [ ! -f "$3" ]; then
            echo "./${0##*/}: couldn't read \`$3\`: No such file or directory" >/dev/stderr
            exit 1
          fi
          apply_snapshot "$2" "$3"
        else
          usage
        fi
      ;;
    -*) echo "${0##*/}: unknown option: $1" >&2; usage ;;
  esac
else
  usage
fi


